{{- if index .Values "demo" "ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxdemos-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
    host: my-dummy-host.com
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxdemos-svc
            port:
              number: 80
{{- end }}
